name: gen3_workflow CI using /cvmfs/sw.lsst.eu

on:
    push:
        branches:
            - master
            - u/jchiang/gen3_scripts

    pull_request:
        branches:
            - master
            - u/jchiang/gen3_scripts

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ ubuntu-latest ]
                py: [ "3.12" ]
                CC: [ gcc ]
                CXX: [ g++ ]

        defaults:
            run:
                shell: bash -l {0}

        steps:
            - uses: actions/checkout@v2
            - uses: cvmfs-contrib/github-action-cvmfs@v4
            - name: Set up /cvmfs/sw.lsst.eu
              run: |
                curl -OL https://github.com/airnandez/sw-lsst-eu/releases/download/v0.7/cvmfs-config-lsst_0.7_all.deb
                sudo dpkg -i cvmfs-config-lsst_0.7_all.deb

            - name: Clone the package and checkout the branch
              shell: bash -l {0}
              run: |
                git clone https://github.com/${GITHUB_REPOSITORY}
                cd gen3_workflow
                git fetch origin ${GITHUB_REF}:TESTING
                git checkout TESTING

            - name: Run the test pipelines
              run: |
                LSST_DISTRIB_ROOT=/cvmfs/sw.lsst.eu/almalinux-x86_64/lsst_distrib
                LATEST_VERSION=`/usr/bin/ls -rt ${LSST_DISTRIB_ROOT} | grep w_20 | tail -n 1`
                source ${LSST_DISTRIB_ROOT}/${LATEST_VERSION}/loadLSST-ext.bash
                setup lsst_distrib
                eups list lsst_distrib
                setup -r . -j
                cd tests
                pytest test_query_workflow.py test_bps_restart.py
